// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa90b0r-KCBxIJ8ZohfXESFGofjK8g-Nc',
    appId: '1:470214857625:web:c59260adcb7ab5d95ff908',
    messagingSenderId: '470214857625',
    projectId: 'better-together-deed2',
    authDomain: 'better-together-deed2.firebaseapp.com',
    storageBucket: 'better-together-deed2.firebasestorage.app',
    measurementId: 'G-1GZLQS4T39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGxW_Dyi8E17pEWmKuzTJr9gNkdEFhBb8',
    appId: '1:470214857625:android:0f35416fbcd3b1d65ff908',
    messagingSenderId: '470214857625',
    projectId: 'better-together-deed2',
    storageBucket: 'better-together-deed2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCepgIcWt_uxli5PTg1V7VDA4l4yR-obQ',
    appId: '1:470214857625:ios:63988f3a15a939175ff908',
    messagingSenderId: '470214857625',
    projectId: 'better-together-deed2',
    storageBucket: 'better-together-deed2.firebasestorage.app',
    iosBundleId: 'com.example.betterTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCepgIcWt_uxli5PTg1V7VDA4l4yR-obQ',
    appId: '1:470214857625:ios:63988f3a15a939175ff908',
    messagingSenderId: '470214857625',
    projectId: 'better-together-deed2',
    storageBucket: 'better-together-deed2.firebasestorage.app',
    iosBundleId: 'com.example.betterTogether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa90b0r-KCBxIJ8ZohfXESFGofjK8g-Nc',
    appId: '1:470214857625:web:b30737e223261a255ff908',
    messagingSenderId: '470214857625',
    projectId: 'better-together-deed2',
    authDomain: 'better-together-deed2.firebaseapp.com',
    storageBucket: 'better-together-deed2.firebasestorage.app',
    measurementId: 'G-HX779RG8NE',
  );
}
